export const initialTasks = [
  {
    id: 1,
    name: "Ibu Sari",
    address: "Jl. Merdeka No.12, Kecamatan A",
    note: "Sampah organik + plastik",
    lat: -6.200392,
    lng: 106.816048,
    status: "pending",
    weight: null,
    category: null,
  },
  {
    id: 2,
    name: "Bapak Anton",
    address: "Perumahan B, Blok C3",
    note: "Rumah tangga - Kode 22",
    lat: -6.201234,
    lng: 106.817123,
    status: "pending",
    weight: null,
    category: null,
  },
  {
    id: 3,
    name: "Bu Wati",
    address: "Pasar Tradisional, Kios 5-6",
    note: "Sampah basah + kertas",
    lat: -6.202345,
    lng: 106.818234,
    status: "on-process",
    weight: null,
    category: null,
  },
]